//AUTH AND DASHBOARD

export const DASHBOARD_RECENT_PROJECTS = 'DASHBOARD_RECENT_PROJECTS';
export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS ';
export const USER_PROFILE = 'USER_PROFILE';
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const LOGOUT = 'LOGOUT';

// NOTIFICATIONS

export const GET_MESSAGES = 'GET_MESSAGES';
export const READ_MESSAGE = 'READ_MESSAGE';
export const GET_SENDED_MESSAGES = 'GET_SENDED_MESSAGES';
export const GET_SENDED_MESSAGE_DETAIL = 'GET_SENDED_MESSAGE_DETAIL';
export const GET_RECEIVED_MESSAGE_DETAIL = 'GET_RECEIVED_MESSAGE_DETAIL';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';

// TASKS
export const GET_PRIORITIES = 'GET_PRIORITIES';

// PROJECTS

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';

// PROJECT FILES

export const SEARCH_FILES = 'SEARCH_FILES';
