export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const SET_USER_AND_AUTH = 'SET_USER_AND_AUTH';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const GET_SETTINGS = 'GET_SETTINGS';
