import { makeStyles } from '@material-ui/core';

const passwordPanelStyles = makeStyles((theme) => ({
  disciplineTitleStyle: {
    fontSize: '16px',
    lineHeight: '16px',
    fontWeight: '400',
    letterSpacing: '-0.2px',
    marginBottom: '24px',
  },
  disciplineStyle: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  keywordStyle: {
    backgroundColor: '#089BAB',
    color: '#ffffff',
    fontSize: '14px',
    lineHeight: '16px',
    letterSpacing: '-0.2px',
    fontFamily: 'Poppins',
    fontWeight: '400',
    borderRadius: '16px',
    padding: '8px 12px',
    marginRight: '16px',
    marginBottom: '40px',
    '&:hover, &:focus': {
      backgroundColor: '#089BAB',
    },
    '& > span': {
      padding: '0',
    },
    '& > svg': {
      color: '#ffffff',
      width: '14px',
      height: '14px',
      marginLeft: '8px',
      marginRight: '0',
    },
    '& > svg:hover': {
      color: '#DE6262',
      backgroundColor: '#ffffff',
      borderRadius: '2px',
    },
  },
  addKeywordStyle: {
    border: '1px solid #089BAB',
    backgroundColor: '#ffffff',
    color: '#089BAB',
    fontFamily: 'Poppins',
    fontSize: '14px',
    lineHeight: '16px',
    letterSpacing: '-0.2px',
    fontWeight: '400',
    borderRadius: '16px',
    padding: '8px 12px',
    marginRight: '16px',
    marginBottom: '40px',
    cursor: 'pointer',
    '& > span': {
      padding: '0',
    },
    '& > svg': {
      color: '#089BAB !important',
      width: '16px !important',
      height: '16px !important',
      marginLeft: '0 !important',
      marginRight: '10px !important',
    },
  },
  modalTitle: {
    padding: '0',
    '& h2': {
      fontFamily: 'Montserrat',
      fontWeight: '400',
      fontSize: '18px',
      lineHeight: '16px',
      letterSpacing: '-0.2px',
      color: '#089BAB',
      padding: '20px 20px 0',
    },
  },
  modalContent: {
    display: 'flex',
    padding: '20px',
    '& > p': {
      fontSize: '14px',
      lineHeight: '20px',
      fontWeight: '400',
      fontFamily: 'Poppins',
      color: '#4D4D4D',
      margin: '0px',
    },
  },
  modalAction: {
    padding: '0 20px 16px',
  },
  chipIcon: {
    borderBottom: '1px solid rgba(29, 32, 32, 0.1) !important',
  },
  chipStyle: {
    paddingLeft: '2px',
    '& > div': {
      marginBottom: '0px',
    },
    '& input': {
      fontSize: '14px',
      lineHeight: '16px',
      fontFamily: 'Poppins',
      fontWeight: '400',
      marginLeft: '8px',
    },
    '& input::placeholder': {
      color: '#4D4D4D',
      fontFamily: 'Poppins',
      fontSize: '12px',
      lineHeight: '16px',
      letterSpacing: '-0.2px',
    },
    '& > div:before, & > div:after': {
      borderBottom: '1px solid rgba(29, 32, 32, 0.1) !important',
    },
    '& > div:after': {
      transform: 'scaleX(0) !important',
    },
  },
  chipAddItemStyle: {
    backgroundColor: '#EDF5F6',
    padding: '8px 12px',
    marginBottom: '8px',
    marginLeft: '8px',
    '& > span': {
      padding: '0 8px 0 0',
      fontSize: '14px',
      lineHeight: '16px',
      fontFamily: 'Poppins',
      fontWeight: '400',
      letterSpacing: '-0.2px',
      height: '16px',
    },
    '& > svg': {
      margin: '0',
      width: '16px',
      height: '16px',
      color: '#089BAB',
    },
  },
  deleteKeywordButton: {
    backgroundColor: '#DE6262 !important',
    padding: '10px 16px',
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: '500',
    fontFamily: 'Poppins',
    color: '#ffffff',
    borderRadius: '10px',
    textTransform: 'none',
    '& svg': {
      color: '#ffffff',
      width: '16px',
      height: '16px',
      marginRight: '12px',
    },
  },
  deleteCancelKeywordButton: {
    backgroundColor: '#858383 !important',
    marginLeft: '10px !important',
    padding: '10px 16px',
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: '600',
    fontFamily: 'Poppins',
    color: '#ffffff',
    borderRadius: '10px',
    textTransform: 'none',
  },
  addKeywordButton: {
    backgroundColor: '#FF8A47 !important',
    padding: '10px 16px',
    fontSize: '12px',
    lineHeight: '16px',
    fontWeight: '500',
    fontFamily: 'Poppins',
    color: '#ffffff',
    borderRadius: '10px',
    textTransform: 'none',
    '& svg': {
      color: '#ffffff',
      width: '16px',
      height: '16px',
      marginRight: '12px',
    },
  },
}));

export default passwordPanelStyles;
